GET http://localhost:3000/books/

### 
POST http://localhost:3000/books HTTP/1.1
content-type: application/json

{
    "author": "Livro Teste3",
    "country": "Teste3",
    "imageLink": "Teste3",
    "language": "teste",
    "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart",
    "pages": 123,
    "title": "Teste",
    "year": 3000,
    "id": "9999999"
}

###
PUT http://localhost:3000/books/:555 HTTP/1.1
content-type: application/json
{
    "author": "Livro Teste Editado",
    "country": "Teste",
    "imageLink": "Teste",
    "language": "teste",
    "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart",
    "pages": 123,
    "title": "Teste",
    "year": 3000,
    "id": "555",
}


###
DELETE http://localhost:3000/books/
